apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.services.helloWorld.meta.argocd.syncWave | quote }}
spec:
  replicas: {{ .Values.services.helloWorld.http.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      terminationGracePeriodSeconds: 90
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: hello-world
      containers:
        - name: hello-world
          image: '{{ .Values.services.helloWorld.image.repository }}:{{ required "commitSha must be set (--set commitSha=$GITHUB_SHA)" .Values.commitSha }}'
          command: ["poetry", "run", "uvicorn"]
          args:
            - "hello_world.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8080"
            - "--timeout-keep-alive"
            - "75"
          envFrom:
            - secretRef:
                name: hello-world
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
          readinessProbe:
            httpGet:
              path: /readiness-check
              port: http
