infra:
  meta:
    region: eu-central-1
    argocd:
      syncWave: -10
  externalSecrets:
    serviceAccount:
      roleArn: arn:aws:iam::258167965416:role/ticketmaster-test-eu-eso
  services:
    helloWorld:
      secrets:
        prefix: ticketmaster/hello-world/test-eu
    ticketmaster:
      secrets:
        prefix: ticketmaster/ticketmaster/test-eu

services:
  helloWorld:
    meta:
      argocd:
        syncWave: 0
    image:
      repository: 258167965416.dkr.ecr.eu-central-1.amazonaws.com/hello-world
    http:
      replicas: 1
    migrations:
      expand:
        meta:
          argocd:
            syncWave: -5
      contract:
        meta:
          argocd:
            syncWave: 5
  ticketmaster:
    meta:
      argocd:
        syncWave: 0
    image:
      repository: 258167965416.dkr.ecr.eu-central-1.amazonaws.com/ticketmaster
    http:
      hpa:
        minReplicas: 1
        maxReplicas: 3
        cpuTargetPercent: 70
    migrations:
      expand:
        meta:
          argocd:
            syncWave: -5
      contract:
        meta:
          argocd:
            syncWave: 5
