commitSha: ""

infra:
  meta:
    argocd:
      syncWave: 0
    region: ""
  externalSecrets:
    serviceAccount:
      roleArn: ""
  frontend:
    secrets:
      prefix: ""
  services:
    helloWorld:
      secrets:
        prefix: ""
    ticketmaster:
      secrets:
        prefix: ""

frontend:
  meta:
    argocd:
      syncWave: 0
  image:
    repository: ""
  http:
    replicas: 1

ingress:
  meta:
    argocd:
      syncWave: 0

services:
  helloWorld:
    meta:
      argocd:
        syncWave: 0
    image:
      repository: ""
    http:
      replicas: 1
    migrations:
      expand:
        meta:
          argocd:
            syncWave: 0
      contract:
        meta:
          argocd:
            syncWave: 0
  ticketmaster:
    meta:
      argocd:
        syncWave: 0
    image:
      repository: ""
    http:
      hpa:
        minReplicas: 1
        maxReplicas: 1
        cpuTargetPercent: 70
    migrations:
      expand:
        meta:
          argocd:
            syncWave: 0
      contract:
        meta:
          argocd:
            syncWave: 0
