infra:
  meta:
    region: eu-central-1
    argocd:
      syncWave: -10
  externalSecrets:
    serviceAccount:
      roleArn: arn:aws:iam::258167965416:role/ticketmaster-test-eu-eso
  frontend:
    secrets:
      prefix: ticketmaster/frontend/test-eu
  services:
    ticketmaster:
      secrets:
        prefix: ticketmaster/ticketmaster/test-eu

frontend:
  meta:
    argocd:
      syncWave: 0
  image:
    repository: 258167965416.dkr.ecr.eu-central-1.amazonaws.com/frontend
  http:
    replicas: 1

ingress:
  meta:
    argocd:
      syncWave: 0

services:
  ticketmaster:
    meta:
      argocd:
        syncWave: 0
    image:
      repository: 258167965416.dkr.ecr.eu-central-1.amazonaws.com/ticketmaster
    http:
      hpa:
        minReplicas: 1
        maxReplicas: 3
        cpuTargetPercent: 70
    migrations:
      expand:
        meta:
          argocd:
            syncWave: -5
      contract:
        meta:
          argocd:
            syncWave: 5
