apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.infra.postgres.meta.argocd.syncWave | quote }}
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
