[group('run')]
run-frontend-dev:
    cd frontend && npm run dev

[group('run')]
build-frontend:
    cd frontend && npm run build

[group('run')]
docker-build-frontend:
    docker build -t frontend:local frontend/

[group('run')]
docker-run-frontend backend_url:
    docker run --rm -p 8080:80 -e BACKEND_URL={{backend_url}} frontend:local
