[tool.poetry]
name = "hello-world"
version = "0.4.0"
description = "Hello-world FastAPI canary for EKS migration"
authors = ["Aleksei Sosov <forgithublesh@yandex.ru>"]
packages = [{ include = "hello_world" }]

[tool.poetry.dependencies]
python = "^3.14"
fastapi = {extras = ["standard"], version = "^0.136.0"}
uvicorn = "^0.44.0"
ticketmaster-libs = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
