apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  labels:
    app: pgbouncer
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.infra.pgbouncer.meta.argocd.syncWave | quote }}
spec:
  type: ClusterIP
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      port: 5432
      targetPort: pgbouncer
      protocol: TCP
