apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store-parameter-store
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.infra.meta.argocd.syncWave | quote }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.infra.meta.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: eso
            namespace: default
