apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.infra.meta.argocd.syncWave | quote }}
    eks.amazonaws.com/role-arn: {{ .Values.infra.externalSecrets.serviceAccount.roleArn | quote }}
