---
# Source: ticketmaster/templates/services/ticketmaster/migrations/contract/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ticketmaster-migrate-contract
  labels:
    app: ticketmaster-migrate-contract
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: ticketmaster-migrate-contract
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: '258167965416.dkr.ecr.eu-central-1.amazonaws.com/ticketmaster:b2a085749fa66a00bd4517469b3c508c5b8544b6'
          command: ["poetry", "run", "alembic", "upgrade", "contract@head"]
          envFrom:
            - secretRef:
                name: ticketmaster
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
