---
# Source: ticketmaster/templates/infra/frontend/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend
  labels:
    app: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    force-sync: "974cce94ecab3cf830800f07db37b8c9e01f68b8"
spec:
  refreshInterval: 1h
  target:
    name: frontend
    creationPolicy: Owner
  data:
    - secretKey: BACKEND_URL
      remoteRef:
        key: /ticketmaster/frontend/test-eu/BACKEND_URL
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: COGNITO_USER_POOL_ID
      remoteRef:
        key: /ticketmaster/frontend/test-eu/COGNITO_USER_POOL_ID
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: COGNITO_USER_POOL_CLIENT_ID
      remoteRef:
        key: /ticketmaster/frontend/test-eu/COGNITO_USER_POOL_CLIENT_ID
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: COGNITO_DOMAIN
      remoteRef:
        key: /ticketmaster/frontend/test-eu/COGNITO_DOMAIN
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
