apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hello-world
  labels:
    app: hello-world
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.infra.argocd.syncWave | quote }}
    force-sync: {{ .Values.commitSha | quote }}
spec:
  refreshInterval: 1h
  target:
    name: hello-world
    creationPolicy: Owner
  data:
    - secretKey: SECRET
      remoteRef:
        key: {{ .Values.helloWorld.secrets.prefix }}/SECRET
      sourceRef:
        storeRef:
          name: hello-world-secrets-manager
          kind: ClusterSecretStore
    - secretKey: ENVIRONMENT
      remoteRef:
        key: /{{ .Values.helloWorld.secrets.prefix }}/ENVIRONMENT
      sourceRef:
        storeRef:
          name: hello-world-parameter-store
          kind: ClusterSecretStore
