apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.infra.argocd.syncWave | quote }}
    eks.amazonaws.com/role-arn: {{ .Values.eso.serviceAccount.roleArn | quote }}
