apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
  labels:
    app: postgres
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.infra.meta.argocd.syncWave | quote }}
    force-sync: {{ .Values.commitSha | quote }}
spec:
  refreshInterval: 1h
  target:
    name: postgres
    creationPolicy: Owner
  data:
    - secretKey: SUPERUSER_PASSWORD
      remoteRef:
        key: {{ .Values.infra.externalSecrets.postgres.prefix }}/SUPERUSER_PASSWORD
      sourceRef:
        storeRef:
          name: aws-secret-store-secrets-manager
          kind: ClusterSecretStore
    - secretKey: APP_PASSWORD
      remoteRef:
        key: {{ .Values.infra.externalSecrets.postgres.prefix }}/APP_PASSWORD
      sourceRef:
        storeRef:
          name: aws-secret-store-secrets-manager
          kind: ClusterSecretStore
