---
# Source: ticketmaster/templates/infra/services/hello-world/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hello-world
  labels:
    app: hello-world
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    force-sync: "40ceae9a72248a22c057e17846721f4ed18fc0f6"
spec:
  refreshInterval: 1h
  target:
    name: hello-world
    creationPolicy: Owner
  data:
    - secretKey: SECRET
      remoteRef:
        key: ticketmaster/hello-world/test-eu/SECRET
      sourceRef:
        storeRef:
          name: aws-secret-store-secrets-manager
          kind: ClusterSecretStore
    - secretKey: ENVIRONMENT
      remoteRef:
        key: /ticketmaster/hello-world/test-eu/ENVIRONMENT
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
