---
# Source: ticketmaster/templates/infra/services/ticketmaster/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ticketmaster
  labels:
    app: ticketmaster
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    force-sync: "76316e61adb135ed0e3e5827abee4a4819d5f933"
spec:
  refreshInterval: 1h
  target:
    name: ticketmaster
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB_URL
      remoteRef:
        key: ticketmaster/ticketmaster/test-eu/POSTGRES_DB_URL
      sourceRef:
        storeRef:
          name: aws-secret-store-secrets-manager
          kind: ClusterSecretStore
    - secretKey: REDIS_URL
      remoteRef:
        key: ticketmaster/ticketmaster/test-eu/REDIS_URL
      sourceRef:
        storeRef:
          name: aws-secret-store-secrets-manager
          kind: ClusterSecretStore
    - secretKey: SECRET
      remoteRef:
        key: ticketmaster/ticketmaster/test-eu/SECRET
      sourceRef:
        storeRef:
          name: aws-secret-store-secrets-manager
          kind: ClusterSecretStore
    - secretKey: SENTRY_DSN
      remoteRef:
        key: ticketmaster/ticketmaster/test-eu/SENTRY_DSN
      sourceRef:
        storeRef:
          name: aws-secret-store-secrets-manager
          kind: ClusterSecretStore
    - secretKey: ENVIRONMENT
      remoteRef:
        key: /ticketmaster/ticketmaster/test-eu/ENVIRONMENT
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: SENTRY_SEND_PII
      remoteRef:
        key: /ticketmaster/ticketmaster/test-eu/SENTRY_SEND_PII
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: SENTRY_TRACES_SAMPLE_RATE
      remoteRef:
        key: /ticketmaster/ticketmaster/test-eu/SENTRY_TRACES_SAMPLE_RATE
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: AWS_REGION
      remoteRef:
        key: /ticketmaster/ticketmaster/test-eu/AWS_REGION
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: JWT_AUDIENCE
      remoteRef:
        key: /ticketmaster/ticketmaster/test-eu/JWT_AUDIENCE
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: LAMBDA_JWT_KMS_KEY_ARN
      remoteRef:
        key: /ticketmaster/ticketmaster/test-eu/LAMBDA_JWT_KMS_KEY_ARN
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: LAMBDA_JWT_ISSUER
      remoteRef:
        key: /ticketmaster/ticketmaster/test-eu/LAMBDA_JWT_ISSUER
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: ADMIN_JWT_KMS_KEY_ARN
      remoteRef:
        key: /ticketmaster/ticketmaster/test-eu/ADMIN_JWT_KMS_KEY_ARN
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: ADMIN_JWT_ISSUER
      remoteRef:
        key: /ticketmaster/ticketmaster/test-eu/ADMIN_JWT_ISSUER
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
    - secretKey: COGNITO_AUDIENCE
      remoteRef:
        key: /ticketmaster/ticketmaster/test-eu/COGNITO_AUDIENCE
      sourceRef:
        storeRef:
          name: aws-secret-store-parameter-store
          kind: ClusterSecretStore
