---
# Source: ticketmaster/templates/infra/services/ticketmaster/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticketmaster
  labels:
    app: ticketmaster
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
