---
# Source: ticketmaster/templates/services/ticketmaster/migrations/expand/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ticketmaster-migrate-expand
  labels:
    app: ticketmaster-migrate-expand
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: ticketmaster-migrate-expand
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: '258167965416.dkr.ecr.eu-central-1.amazonaws.com/ticketmaster:76316e61adb135ed0e3e5827abee4a4819d5f933'
          command: ["poetry", "run", "alembic", "upgrade", "expand@head"]
          envFrom:
            - secretRef:
                name: ticketmaster
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
