---
# Source: ticketmaster/templates/infra/external-secrets/aws-secret-store-parameter-store.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store-parameter-store
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso
            namespace: default
