---
# Source: ticketmaster/templates/infra/external-secrets/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    eks.amazonaws.com/role-arn: "arn:aws:iam::258167965416:role/ticketmaster-test-eu-eso"
