name: Deploy to Test

on:
  push:
    branches:
      - "test/**"

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-test-eu
  cancel-in-progress: false

jobs:
  publish-libs:
    uses: ./.github/workflows/called-publish-python-package.yaml
    with:
      environment: test-eu
      package_path: src/libs
    secrets: inherit

  publish-services-docker-images:
    needs: [publish-libs]
    uses: ./.github/workflows/called-publish-docker-images.yaml
    with:
      environment: test-eu
    secrets: inherit

  helm-upgrade-infra:
    uses: ./.github/workflows/called-helm-upgrade.yaml
    with:
      environment: test-eu
      chart: infra
    secrets: inherit

  helm-upgrade-application:
    needs: [publish-services-docker-images, helm-upgrade-infra]
    uses: ./.github/workflows/called-helm-upgrade.yaml
    with:
      environment: test-eu
      chart: application
    secrets: inherit

  deploy-cognito-pre-signup-lambda:
    uses: ./.github/workflows/called-deploy-lambda.yaml
    with:
      environment: test-eu
      lambda_name: ticketmaster-cognito-pre-signup-test-eu
      lambda_path: src/lambdas/cognito_pre_signup
    secrets: inherit
