name: Deploy to Test

on:
  push:
    branches:
      - "test/**"

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-test-eu
  cancel-in-progress: false

jobs:
  publish-libs:
    uses: ./.github/workflows/called-publish-python-package.yaml
    with:
      environment: test-eu
      package_path: src/libs
    secrets: inherit

  deploy-ticketmaster:
    needs: [publish-libs]
    uses: ./.github/workflows/called-deploy-container-service.yaml
    with:
      environment: test-eu
      service_name: ticketmaster
      service_path: src/ticketmaster
      run_migrations: true
    secrets: inherit

  deploy-cognito-pre-signup-lambda:
    needs: [publish-libs]
    uses: ./.github/workflows/called-deploy-lambda.yaml
    with:
      environment: test-eu
      lambda_name: ticketmaster-cognito-pre-signup-test-eu
      lambda_path: src/lambdas/cognito_pre_signup
    secrets: inherit

  deploy-frontend:
    needs: [publish-libs]
    uses: ./.github/workflows/called-deploy-container-service.yaml
    with:
      environment: test-eu
      service_name: frontend
      service_path: frontend
      run_migrations: false
    secrets: inherit
